name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Already created tag"
        required: true

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set build version
        run: |
          set -e
          [[ "${{ github.event.inputs.tag }}" =~ ^v[0-9.]+$ ]] || exit 1
          INPUT_TAG=${{ github.event.inputs.tag }}
          tag=${INPUT_TAG##*/}
          tag_version=${INPUT_TAG##*/v}
          echo "BUILD_TAG=${tag}" >> $GITHUB_ENV
          echo "DOCKER_TAG_VERSION=${tag_version}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:docker"
          file: release.Dockerfile
          build-args: |
            TAG=${{ env.BUILD_TAG }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: devld/go-drive:latest,devld/go-drive:${{ env.DOCKER_TAG_VERSION }}
